### PR TITLE
Validate the config before calling into the bot

### LINKED ISSUE #9: Allow configuration:guild to be non-existent
Currently if there are no guilds in the configuration file we crash the bot:

```
D:\Libraries\Documents\GitHub\gameon\bot.js:58
        this.configuration_.guilds[msg.guild.id] = this.configuration_.guilds[msg.guild.id] || {"games": {}};
                                                                             ^

TypeError: Cannot read property '418576365860683793' of undefined
    at Bot.onMessage (D:\Libraries\Documents\GitHub\gameon\bot.js:58:78)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at MessageCreateHandler.handle (D:\Libraries\Documents\GitHub\gameon\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (D:\Libraries\Documents\GitHub\gameon\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (D:\Libraries\Documents\GitHub\gameon\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (D:\Libraries\Documents\GitHub\gameon\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (D:\Libraries\Documents\GitHub\gameon\node_modules\ws\lib\event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
```

### PR DESCRIPTION
**Pull request by stephenmcgruer**
Fixes #9

### CODE REVIEW

File: run.js [hunk 1]
```diff
@@ -10,12 +10,25 @@ function save(configuration) {
       console.error('Error saving configuration');
   });
 };
+
+function validateConfig(configuration) {
```
Comment (stephenmcgruer) [inline run.js:14]: Arguably a terrible name.

**Review by flackr — APPROVED** [review]
